# Generated by Django 3.0.4 on 2021-02-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='counter',
        ),
    ]
